
module.exports ={
    nameProperties:{
        inputName:'name',
        validation:[
            {
                isEmpty:true
            },
            {
                isLength:{min:4}
            }
        ]
    },
    slugProperties:{
        inputName:'slug',
        validation:[
            {
                isEmpty:false
            },
            {
                isLength:{min:5}
            }
            ,
            {
                isAlphabets:true,
            },
        ]
    }
}