export const GLOBAL = {
  SET_LANGUAGE: "SET_LANGUAGE",
  SET_SEARCH: "SET_SEARCH",
  SET_ROUTE: "SET_ROUTE",
};


export const USER = {
  SET_USER: "SET_USER",
  REMOVE_USER: "REMOVE_USER",
};

export const PAGE = {
  SET_PAGE_NUMBER: "PAGE_NUMBER",
  SET_NUMBER_ITEMS_PER_PAGE: "NUMBER_ITEMS",
};
